Changed Appveyor configuration to run tests with my local version of R.
Trying to solve Appveyor error:
"> library(testthat)
Error: package or namespace load failed for 'testthat':
 package 'testthat' was installed by an R version with different internals; it needs to be reinstalled for use with this R version
Execution halted"